### ISSUE TITLE
Clear inactive users or automatically prune inactive users

### ISSUE THREAD

**Issue by nightpool** [biharygergo/card-estimator#173]
Often, we have users who have to join from their phone or another device, creating duplicate users in our rooms. Having a "clear inactive users" button or a feature that hides users who haven't been active recently would make it much easier to read / understand the voting list and prevent us from having to make new rooms very frequently. Probably the easiest way to implement this would be to add a "hidden" field on users that gets unset when they submit a vote, and then let other users in the room set that field. An alternative (and maybe better) fix would be to just hide users automatically if they're not active. This could be done with a very simple "heartbeat" process that sets a `lastActiveAt` in the user's firebase record every few minutes, and then automatically just filtering out `lastActiveAt < 30.minutes.ago` users from the room display.

**Comment by biharygergo** [comment]
Hey @nightpool!

Thanks for opening an issue, it's always great to hear from users of this project! 🙏

Removing a user from a room is a supported feature for Premium subscribers - though it's a bit hidden. If you go to Settings > Security & permissions > Members (tab) you'll see "Remove from room" as an option for each member. 

Could I ask why you'd like to reuse a room rather than create a new one for each planning session? Understanding your use-case will help develop this or other features in the future.

Thanks!

**Comment by nightpool** [comment]
It's just a little more convenient for our product manager to have the same tab open rather then having to go through the "create a new room" flow each time!

**Comment by biharygergo** [comment]
There is actually a feature made specifically for that use case. "Recurring meetings" allows you to create a single link that redirects to a lobby where the host can start a new room every time. Team members will automatically be redirected to the current room. It's best to put the recurring link into a calendar invite and that's it. 

You can find this under "My organization > Recurring meetings".

**Comment by katmossa** [comment]
We use it in the same way as @nightpool described in my project - its easier to share one link among team members druing Backlog refinement. Maybe having a new functionality to remove particular person from the planning session as admin would be better idea.

**Comment by katmossa** [comment]
yep we use it the same way as @nightpool described in my project and having 3 ppl with the same name everytime is a bit annoying ;/ cant force them to check out their session and leave it manually

**Comment by biharygergo** [comment]
Hey @katmossa, thanks for your feedback! I've taken this into consideration and will add the ability to remove a member from the room for admins to the free version. It should be available by tomorrow. 

I do wonder though what's the best way to handle this "single-room" scenario. Can you also describe how you are using the single room? How long are you using one room and how often do you join it? How do you share the room ID/link with the team?

I wonder if there was a button to "Start a new room" and you could select participants to "transfer" to the new, clean room - would that work well for you? I'm concerned about using these long-running rooms as there is a theoretical limit to how big a document can grow in Firebase and if you have hundreds of rounds, you'll likely reach it. Multiple rooms are also better supported by other features, such as the velocity widget and the round history page. What do you think?

**Comment by katmossa** [comment]
Hello @biharygergo ;) 
That would be great ! Thank you ;) 

We are using planning poker for our backlog refinement meetings which are scheduled once per week. One room was created I guess couples months ago and right now person responsible for discussing all of the stories prepare their titles by deleting previous rounds from the same room and add new ones. Everyone from the team just join the room which link is pinned in the chat. I guess for them its easier to delete rounds in already created room because sometimes some of the stories are not refined (out of time) and then we are keeping them for the next refinement meeting and just deleting that were already refined and adding next ones.

**Comment by biharygergo** [comment]
Hey @katmossa, @nightpool - I've added this feature, so you'll be able to remove someone from the room by hovering their avatar and clicking on "Remove from room". This will remove the member from the room but keep their historical votes in the sidebar and when downloading results as .csv. Let me know if this works for you.

Is there any other feedback or improvement idea you have for the app? :) 

Thank you!

**Comment by katmossa** [comment]
@biharygergo feature is working like a charm :) thank you !
If we figure out some new improvements I will definitely let you know ;)
